FROM python:3
WORKDIR /usr/src/app
COPY requirements.txt .
RUN apt-get update && apt-get -y install cmake protobuf-compiler
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "app.py"]